cargo-features = ["edition2021"]

[package]
name = "kata-ml-interface"
version = "0.1.0"
edition = "2021"

[dependencies]
cstr_core = { version = "0.2.3", default-features = false }
kata-memory-interface = { path = "../../MemoryManager/kata-memory-interface" }
