[package]
name = "kata-security-interface"
version = "0.1.0"
edition = "2018"

[dependencies]
postcard = "0.7"
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
serde-big-array = "0.3"
