[package]
name = "kata-ml-coordinator"
version = "0.1.0"
authors = ["Adam Jesionowski <jesionowski@google.com>"]
edition = "2018"

[dependencies]
kata-logger = { path = "../../DebugConsole/kata-logger" }
kata-panic = { path = "../../DebugConsole/kata-panic" }
log = "0.4"

[lib]
name = "kata_ml_coordinator"
path = "src/run.rs"
crate-type = ["staticlib"]
