[package]
name = "kata-process-manager"
version = "0.1.0"
description = "Kata OS ProcessManager services"
edition = "2018"

[dependencies]
arrayvec = { version = "0.7", default-features = false }
kata-proc-common = { path = "../kata-proc-common" }
linked_list_allocator = "0.9"
panic-halt = "0.2.0"

[lib]
name = "kata_process_manager"
path = "src/run.rs"
crate-type = ["staticlib"]
