[package]
name = "kata-process-manager"
version = "0.1.0"
description = "Kata OS ProcessManager services"
edition = "2018"

[dependencies]
arrayvec = { version = "0.7", default-features = false }
kata-allocator = { path = "../../DebugConsole/kata-allocator" }
kata-logger = { path = "../../DebugConsole/kata-logger" }
kata-panic = { path = "../../DebugConsole/kata-panic" }
kata-proc-common = { path = "../kata-proc-common" }
log = "0.4"

[lib]
name = "kata_process_manager"
path = "src/run.rs"
crate-type = ["staticlib"]
