[package]
name = "kata-proc-manager"
version = "0.1.0"
description = "Kata OS ProcessManager services"
edition = "2018"

[dependencies]
cstr_core = { version = "0.2.3", default-features = false, features = ["alloc"] }
hashbrown = { version = "0.11", features = ["ahash-compile-time-rng"] }
kata-proc-common = { path = "../kata-proc-common" }
log = "0.4"
smallstr = "0.2"
spin = "0.9"
