[package]
name = "kata-os-common"
version = "0.1.0"
edition = "2018"

[dependencies]
capdl = { path = "src/capdl" }
kata-os-model = { path = "src/kata-os-model" }
sel4-sys = { path = "src/sel4-sys" }
