[package]
name = "slot-allocator"
version = "0.1.0"
authors = ["Sam Leffler <sleffler@google.com>"]
edition = "2021"

[features]
default = []
TRACE_OPS = []

[dependencies]
bitvec = { version = "1.0", default-features = false, features = ["alloc"] }
log = "0.4"
spin = "0.9"
