[package]
name = "kata-storage-manager"
version = "0.1.0"
edition = "2018"

[dependencies]
kata-security-interface = { path = "../../SecurityCoordinator/kata-security-interface" }
kata-storage-interface = { path = "../kata-storage-interface" }
log = "0.4"
