[package]
name = "kata-timer-service"
version = "0.1.0"
edition = "2018"

[dependencies]
kata-os-common = { path = "../../kata-os-common" }
kata-timer-interface = { path = "../kata-timer-interface" }
log = "0.4"
opentitan-timer = { path = "../opentitan-timer" }
spin = "0.9"
