[package]
name = "kata-vec-core"
version = "0.1.0"
edition = "2021"

[dependencies]
kata-io = { path = "../../DebugConsole/kata-io" }
kata-ml-shared = { path = "../kata-ml-shared" }
modular-bitfield = "0.11.2"
log = "0.4"
