[package]
name = "kata-storage-interface"
version = "0.1.0"
edition = "2018"

[dependencies]
cstr_core = "0.2"
kata-security-interface = { path = "../../SecurityCoordinator/kata-security-interface" }
postcard = "0.7"
