[package]
name = "copyregion"
version = "0.1.0"
authors = ["Sam Leffler <sleffler@google.com>"]
edition = "2021"

[dependencies]
log = { version = "0.4", features = ["release_max_level_info"] }
sel4-sys = { path = "../sel4-sys" }
